# Generated by Django 5.2.17 on 2026-09-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='天体名称')),
                ('mu', models.FloatField(blank=True, null=True, verbose_name='标准重力参数 (m³/s²)')),
                ('radius', models.FloatField(blank=True, null=True, verbose_name='半径 (m)')),
                ('has_atmosphere', models.BooleanField(default=False, verbose_name='有大气')),
            ],
            options={
                'verbose_name': '天体',
                'verbose_name_plural': '天体',
                'ordering': ['id'],
            },
        ),
    ]
