# Generated by Django 5.2.17 on 2026-09-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='名称')),
                ('diameter', models.FloatField(blank=True, null=True, verbose_name='直径 (m)')),
                ('dry_mass', models.FloatField(default=0, verbose_name='干重 (t)')),
                ('thrust_asl', models.FloatField(default=0, verbose_name='海平面推力 (kN)')),
                ('thrust_vac', models.FloatField(default=0, verbose_name='真空推力 (kN)')),
                ('isp_asl', models.FloatField(default=0, verbose_name='海平面比冲 (s)')),
                ('isp_vac', models.FloatField(default=0, verbose_name='真空比冲 (s)')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='造价 (√)')),
            ],
            options={
                'verbose_name': '引擎',
                'verbose_name_plural': '引擎',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FuelTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='名称')),
                ('diameter', models.FloatField(blank=True, null=True, verbose_name='直径 (m)')),
                ('dry_mass', models.FloatField(default=0, verbose_name='干重 (t)')),
                ('capacity', models.FloatField(default=0, verbose_name='燃料容量（单位）')),
                ('fuel_type', models.CharField(choices=[('LF_OX', '液体燃料+氧化剂'), ('MONO', '单元推进剂'), ('XENON', '氙气'), ('SOLID', '固体燃料'), ('OTHER', '其他')], default='LF_OX', max_length=10, verbose_name='燃料类型')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='造价 (√)')),
            ],
            options={
                'verbose_name': '燃料罐',
                'verbose_name_plural': '燃料罐',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScienceInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='名称')),
                ('dry_mass', models.FloatField(default=0, verbose_name='干重 (t)')),
                ('experiment_type', models.CharField(blank=True, max_length=40, verbose_name='实验类型')),
                ('data_value', models.FloatField(default=0, verbose_name='基础数据量 (Mits)')),
                ('is_repeatable', models.BooleanField(default=False, verbose_name='可重复使用')),
                ('requires_crew', models.BooleanField(default=False, verbose_name='需要乘员')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='造价 (√)')),
            ],
            options={
                'verbose_name': '科学设备',
                'verbose_name_plural': '科学设备',
                'ordering': ['name'],
            },
        ),
    ]
