# Generated by Django 5.2.17 on 2026-09-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='载荷名称')),
                ('payload_type', models.CharField(choices=[('CREW_CAPSULE', '载人舱'), ('CARGO', '货运舱'), ('SATELLITE', '卫星'), ('PROBE', '探测器'), ('LANDER', '着陆器'), ('OTHER', '其他')], default='OTHER', max_length=12, verbose_name='载荷类型')),
                ('mass', models.FloatField(default=0, verbose_name='质量 (t)')),
                ('diameter', models.FloatField(blank=True, null=True, verbose_name='最小整流罩直径 (m)')),
                ('crew_capacity', models.PositiveIntegerField(default=0, verbose_name='乘员容量')),
                ('has_docking_port', models.BooleanField(default=False, verbose_name='带对接端口')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='造价 (√)')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '有效载荷',
                'verbose_name_plural': '有效载荷',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='火箭名称')),
                ('series', models.CharField(blank=True, max_length=40, verbose_name='系列')),
                ('manufacturer', models.CharField(blank=True, max_length=40, verbose_name='制造商')),
                ('diameter', models.FloatField(blank=True, null=True, verbose_name='最大直径 (m)')),
                ('first_flight_date', models.DateField(blank=True, null=True, verbose_name='首飞日期')),
                ('crew_capacity', models.PositiveIntegerField(default=0, verbose_name='乘员容量')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='造价 (√)')),
                ('is_reusable', models.BooleanField(default=False, verbose_name='可回收复用')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '运载火箭',
                'verbose_name_plural': '运载火箭',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RocketStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_order', models.PositiveIntegerField(verbose_name='级序号')),
                ('engine_count', models.PositiveIntegerField(default=1, verbose_name='引擎数量')),
                ('tank_count', models.PositiveIntegerField(default=0, verbose_name='燃料罐数量')),
                ('structure_mass', models.FloatField(default=0, verbose_name='结构质量 (t)')),
                ('separation_type', models.CharField(choices=[('STACK', '堆叠分离'), ('RADIAL', '径向分离'), ('NONE', '不分离')], default='STACK', max_length=10, verbose_name='分离方式')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '级',
                'verbose_name_plural': '级',
                'ordering': ['stage_order'],
            },
        ),
    ]
