# Generated by Django 5.2.17 on 2026-09-23 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('ops', '0001_initial'),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payload',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='ops.save', verbose_name='所属存档'),
        ),
        migrations.AddField(
            model_name='rocket',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rockets', to='ops.save', verbose_name='所属存档'),
        ),
        migrations.AddField(
            model_name='rocketstage',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='parts.engine', verbose_name='引擎'),
        ),
        migrations.AddField(
            model_name='rocketstage',
            name='fuel_tank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='parts.fueltank', verbose_name='燃料罐'),
        ),
        migrations.AddField(
            model_name='rocketstage',
            name='rocket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='fleet.rocket', verbose_name='所属火箭'),
        ),
        migrations.AddConstraint(
            model_name='rocketstage',
            constraint=models.UniqueConstraint(fields=('rocket', 'stage_order'), name='uniq_rocket_stage_order'),
        ),
    ]
