# Generated by Django 5.2.17 on 2026-09-23 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='发射场名称')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度 (°)')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度 (°)')),
                ('max_mass', models.FloatField(blank=True, null=True, verbose_name='最大起飞质量 (t)')),
                ('is_operational', models.BooleanField(default=True, verbose_name='可用')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='core.body', verbose_name='所在天体')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='ops.save', verbose_name='所属存档')),
            ],
            options={
                'verbose_name': '发射场',
                'verbose_name_plural': '发射场',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Spacecraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='名称')),
                ('craft_type', models.CharField(choices=[('STATION', '空间站'), ('RELAY_SAT', '中继卫星'), ('PROBE', '探测器'), ('ROVER', '探测车'), ('CREWED', '载人飞船'), ('LANDER', '着陆器'), ('OTHER', '其他')], db_index=True, default='OTHER', max_length=14, verbose_name='航天器类型')),
                ('situation', models.CharField(choices=[('ORBITING', '环绕轨道'), ('LANDED', '已着陆'), ('SPLASHED', '水面溅落'), ('FLYING', '大气内飞行'), ('ESCAPING', '逃逸中'), ('DESTROYED', '已损毁')], default='ORBITING', max_length=10, verbose_name='运行状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='在役')),
                ('crew_count', models.PositiveIntegerField(default=0, verbose_name='乘员数')),
                ('sma', models.FloatField(blank=True, help_text='半长轴（天体中心到轨道），不是高度。Kerbin 半径 600 km，所以 100 km 高的圆轨道 sma = 700000。', null=True, verbose_name='半长轴 (m)')),
                ('eccentricity', models.FloatField(blank=True, null=True, verbose_name='离心率')),
                ('inclination', models.FloatField(blank=True, null=True, verbose_name='轨道倾角 (°)')),
                ('cached_period_sec', models.FloatField(blank=True, null=True, verbose_name='周期快照 (s)')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spacecraft', to='core.body', verbose_name='所在天体')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spacecraft', to='ops.save', verbose_name='所属存档')),
                ('source_flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spacecraft', to='ops.flightlog', verbose_name='来源发射')),
            ],
            options={
                'verbose_name': '在轨航天器',
                'verbose_name_plural': '在轨航天器',
                'ordering': ['name'],
            },
        ),
    ]
