# Generated by Django 5.2.17 on 2026-09-23 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='存档名称')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('game_mode', models.CharField(choices=[('CAREER', '生涯模式'), ('SCIENCE', '科研模式'), ('SANDBOX', '沙盒模式')], default='CAREER', max_length=10, verbose_name='存档模式')),
            ],
            options={
                'verbose_name': '玩家存档',
                'verbose_name_plural': '玩家存档',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='任务名称')),
                ('state', models.CharField(choices=[('PLANNED', '计划中'), ('LAUNCHED', '已发射'), ('FAILED', '发射失败'), ('CANCELLED', '已取消')], db_index=True, default='PLANNED', max_length=10, verbose_name='状态')),
                ('planned_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='计划发射日期')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际发射日期')),
                ('crew_count', models.PositiveIntegerField(default=0, verbose_name='乘员数')),
                ('result_code', models.IntegerField(blank=True, help_text='留空=尚未执行；-1=任务失败（火箭工作正常，载荷/设计问题）；0=成功；>0=第 n 级失效（值为失效的级序号）。', null=True, verbose_name='结果编码')),
                ('rest_dv', models.IntegerField(blank=True, help_text='留空=未记录，与「剩余 0」语义不同。', null=True, verbose_name='剩余 Δv (m/s)')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='任务成本 (√)')),
                ('detail', models.TextField(blank=True, verbose_name='任务详情')),
                ('payload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='fleet.payload', verbose_name='有效载荷')),
                ('rocket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='fleet.rocket', verbose_name='运载火箭')),
            ],
            options={
                'verbose_name': '发射日志',
                'verbose_name_plural': '发射日志',
                'ordering': ['-planned_date'],
            },
        ),
    ]
