# Generated by Django 5.2.17 on 2026-09-23 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops', '0001_initial'),
        ('spaceflight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlog',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='spaceflight.site', verbose_name='发射场'),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='ops.save', verbose_name='所属存档'),
        ),
        migrations.AddIndex(
            model_name='flightlog',
            index=models.Index(fields=['state', 'planned_date'], name='ops_flightl_state_fc801b_idx'),
        ),
    ]
